use PRTG;
/*
INSERT INTO dbo.MSK_VICTORIA_SHOP_PRINTERS (PRTG_ID,Shop,Location,IP,MODEL,SERIAL_NUMBER,PC_MONO_START,PC_COLOR_START,Type) VALUES
(82674,'Виктория 11','Заведующие секциями','10.81.11.94','P7035cdn','LWW5905198',2,13,'цветной'),
(82679,'Виктория 45','Администратор','10.81.45.97','P7035cdn','LWW5X05564',0,0,'цветной')
SELECT * FROM dbo.MSK_VICTORIA_SHOP_PRINTERS
WHERE Shop='Виктория 11' or Shop='Виктория 45'
*/
/*
UPDATE dbo.MSK_VICTORIA_SHOP_PRINTERS
SET Location='Администраторская'
WHERE PRTG_ID=82679 

UPDATE dbo.MSK_VICTORIA_SHOP_PRINTERS
SET PC_MONO_END=PAGE_COUNT_MONO
WHERE PRTG_ID=74576 
*/

SELECT Shop,SERIAL_NUMBER,PAGE_COUNT_MONO,PC_MONO_END,PAGE_COUNT_MONO - PC_MONO_END AS Mono, PAGE_COUNT_COLOR - PC_COLOR_END AS Color, Entity FROM dbo.MSK_VICTORIA_SHOP_PRINTERS
WHERE Entity !=0 AND (PC_MONO_END - PC_MONO_START) = 0 AND (PC_COLOR_END - PC_COLOR_START) = 0 AND Shop NOT LIKE 'Архив%'
ORDER BY Shop
