USE master
GO 
ALTER DATABASE SES_ARCHIVE SET single_user WITH rollback immediate
ALTER DATABASE SES_ARCHIVE MODIFY name = SES_ARCHIVE_2015_12_24
ALTER DATABASE SES_ARCHIVE_2015_12_24 SET multi_user WITH rollback immediate
GO
ALTER DATABASE SES_ARCHIVE_TEMP SET single_user WITH rollback immediate
ALTER DATABASE SES_ARCHIVE_TEMP MODIFY name = SES_ARCHIVE
ALTER DATABASE SES_ARCHIVE SET multi_user WITH rollback immediate
GO