CREATE ROLE sapconn LOGIN PASSWORD '#sapboconn%';
-- GRANT to DATABASES
GRANT CONNECT ON DATABASE set TO sapconn;
GRANT CONNECT ON DATABASE set_loyal TO sapconn;
GRANT CONNECT ON DATABASE set_operday TO sapconn;
-- GRANT to existed SCHEMAS
-- FOR SET
\c set
GRANT USAGE ON SCHEMA public TO sapconn;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sapconn;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO sapconn;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO sapconn;
-- GRANT to future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sapconn;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO sapconn;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO sapconn;
-- FOR SET_LOYAL
\c set_loyal
GRANT USAGE ON SCHEMA public TO sapconn;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sapconn;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO sapconn;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO sapconn;
-- GRANT to future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sapconn;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO sapconn;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO sapconn;
-- FOR SET_OPERDAY
\c set_operday
GRANT USAGE ON SCHEMA public TO sapconn;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sapconn;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO sapconn;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO sapconn;
-- GRANT to future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sapconn;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO sapconn;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO sapconn;
\q