CREATE ROLE tester LOGIN PASSWORD 'tester';
-- GRANT to DATABASES
GRANT CONNECT ON DATABASE set TO tester;
GRANT CONNECT ON DATABASE set_loyal TO tester;
GRANT CONNECT ON DATABASE set_operday TO tester;
-- GRANT to existed SCHEMAS
-- FOR SET
\c set
GRANT USAGE ON SCHEMA public TO tester;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tester;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO tester;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO tester;
-- GRANT to future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO tester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO tester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO tester;
-- FOR SET_LOYAL
\c set_loyal
GRANT USAGE ON SCHEMA public TO tester;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tester;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO tester;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO tester;
-- GRANT to future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO tester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO tester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO tester;
-- FOR SET_OPERDAY
\c set_operday
GRANT USAGE ON SCHEMA public TO tester;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tester;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO tester;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO tester;
-- GRANT to future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO tester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO tester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO tester;


Fgfhnfvtyn2016
